maze_io.c File Reference
#include `maze_io.h`
*
Functions
Maze * read_from_file (FILE *f)
void print_maze (Maze *maze)
void print_weight_maze (Maze *maze)
void print_dist_maze (Maze *maze)
void print_pointer_maze (Maze *maze)
Function Documentation
void print_dist_maze (Maze * maze)
duh
References _NODE::distance, get_node(), and MAZE_SIZE.
void print_maze (Maze * maze)
prints a maze
Parameters
maze the maze
References get_node(), MAZE_SIZE, S, and W.
Referenced by main().
void print_pointer_maze (Maze * maze)
duh
References get_node(), and MAZE_SIZE.
void print_weight_maze (Maze * maze)
duh
References get_node(), MAZE_SIZE, and _NODE::weight.
Referenced by flood_fill().
Maze* read_from_file (FILE * f)
these functions read in a .mz file and parse it into a valid maze overall function to create a maze from file. any error will result in a null return.
Returns
a valid maze pointer to the maze struct, null on any sort of error
References create_maze(), E, get_node(), MAZE_SIZE, N, _NODE::neighbors, S, and W.
Referenced by main().