maze.c File Reference
#include `maze.h`
*
Functions
Maze * create_maze ()
allocates and initializes a node allocates a maze of the given size and sets all links in graph to be null. Naturally, it's column major.
Node * create_node ()
allocates and intializes a node allocates a node setting all nighbors to null. Function does NOT allocate for neighbors.
Node * get_node (Maze *maze, int row, int col)
get node by its position this is equlvelant to maze->nodes[x][y]
void update_nodes (bool *walls, Direction dir, Node *no, Node *all, Node *all_neighbor)
uses the information from a sensor read and correctly adds or removes walls from nodes if sensors see a wall, it will remove a connection in the no_wall_node if the sensors don't see a wall, it will add a connection in the all_wall_node
Node * maze_diff (Maze *maze1, Maze *maze2)
bool visited (int row, int col, Direction dir, Maze *maze)
check if a node in a direction is visited looks up (row,col) in maze and checks its neighbors[dir] and returns if that neighbor is known
bool free_maze (Maze *maze)
bool free_node (Node *node)
Function Documentation
Maze* create_maze ()
allocates and initializes a node allocates a maze of the given size and sets all links in graph to be null. Naturally, it's column major.
maze.c implements the functions used to create, free, and manipulate maze
Author
Peter Mitrano
References _NODE::col, create_node(), _MAZE::fastest_route, MAZE_SIZE, _MAZE::nodes, PATH_SIZE, _NODE::row, and _MAZE::solved.
Referenced by flood_explore(), and read_from_file().
Node* create_node ()
allocates and intializes a node allocates a node setting all nighbors to null. Function does NOT allocate for neighbors.
References E, _NODE::known, N, _NODE::neighbors, S, W, and _NODE::weight.
Referenced by create_maze().
bool free_maze (Maze * maze)
free's the maze and all nodes
Parameters
return false on failure
References _MAZE::fastest_route, MAZE_SIZE, and _MAZE::nodes.
Referenced by flood_explore(), and main().
bool free_node (Node * node)
free's a node
Parameters
return false on failure
Node* get_node (Maze * maze, int row, int col)
get node by its position this is equlvelant to maze->nodes[x][y]
References MAZE_SIZE, and _MAZE::nodes.
Referenced by flood_explore(), flood_fill_custom(), maze_diff(), print_dist_maze(), print_maze(), print_maze_mouse(), print_pointer_maze(), read_from_file(), and sense().
Node* maze_diff (Maze * maze1, Maze * maze2)
goes through all the squares in two mazes and compares how many neighbors exist. the highest-difference unvisted node
References get_node(), MAZE_SIZE, _NODE::neighbors, and _NODE::visited.
Referenced by flood_explore().
void update_nodes (bool * walls, Direction dir, Node * no, Node * all, Node * all_neighbor)
uses the information from a sensor read and correctly adds or removes walls from nodes if sensors see a wall, it will remove a connection in the no_wall_node if the sensors don't see a wall, it will add a connection in the all_wall_node
References _NODE::neighbors.
Referenced by flood_explore().
bool visited (int row, int col, Direction dir, Maze * maze)
check if a node in a direction is visited looks up (row,col) in maze and checks its neighbors[dir] and returns if that neighbor is known
References _NODE::known, _NODE::neighbors, and _MAZE::nodes.