maze.h File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <stdbool.h>
*
Classes
struct _NODE
holds its location & neighbors, as well as a bool for indicating if it has been discovered you don't need to free nodes in a maze, just use free_maze however, be sure to free nodes allocated not in mazes I finally gave in an added row and col attributes the node....be very careful you dont get fuck with those. Don't ever move a node around in maze because you risk getting the actual row/col off from the nodes row/col visited is meant for ACTUALLY visiting, known is just used for searching/solving
struct _MAZE
the maze is graph of nodes, stored internally as an matrix. don't forget to call free_maze(maze) after a maze is done being used
Macros
#define MAZE_SIZE (16)
Contains functions for creating and using the Maze and Node structs.
#define PATH_SIZE (100)
Typedefs
typedef enum _DIRECTION Direction
typedef struct _NODE Node
typedef struct _MAZE Maze
Enumerations
enum _DIRECTION { N,
E,
S,
W
 }
Functions
Maze * create_maze ()
allocates and initializes a node allocates a maze of the given size and sets all links in graph to be null. Naturally, it's column major.
Node * create_node ()
allocates and intializes a node allocates a node setting all nighbors to null. Function does NOT allocate for neighbors.
Node * get_node (Maze *maze, int x, int y)
get node by its position this is equlvelant to maze->nodes[x][y]
void update_nodes (bool *walls, Direction dir, Node *no, Node *all, Node *all_neighbor)
uses the information from a sensor read and correctly adds or removes walls from nodes if sensors see a wall, it will remove a connection in the no_wall_node if the sensors don't see a wall, it will add a connection in the all_wall_node
Node * maze_diff (Maze *maze1, Maze *maze2)
bool visited (int row, int col, Direction dir, Maze *maze)
check if a node in a direction is visited looks up (row,col) in maze and checks its neighbors[dir] and returns if that neighbor is known
bool free_maze (Maze *maze)
bool free_node (Node *node)
Macro Definition Documentation
#define MAZE_SIZE (16)
Contains functions for creating and using the Maze and Node structs.
maze.h
Referenced by create_maze(), flood_explore(), flood_fill_custom(), forward(), free_maze(), get_node(), isCenter(), maze_diff(), print_dist_maze(), print_maze(), print_maze_mouse(), print_neighbor_maze(), print_pointer_maze(), print_weight_maze(), and read_from_file().
#define PATH_SIZE (100)
Referenced by create_maze(), flood_explore(), and flood_fill_custom().
Typedef Documentation
typedef enum _DIRECTION Direction
typedef struct _MAZE Maze
typedef struct _NODE Node
Enumeration Type Documentation
enum _DIRECTION
Enumerator
N
E
S
W
Function Documentation
Maze* create_maze ()
allocates and initializes a node allocates a maze of the given size and sets all links in graph to be null. Naturally, it's column major.
maze.c implements the functions used to create, free, and manipulate maze
Author
Peter Mitrano
References _NODE::col, create_node(), _MAZE::fastest_route, MAZE_SIZE, _MAZE::nodes, PATH_SIZE, _NODE::row, and _MAZE::solved.
Referenced by flood_explore(), and read_from_file().
Node* create_node ()
allocates and intializes a node allocates a node setting all nighbors to null. Function does NOT allocate for neighbors.
References E, _NODE::known, N, _NODE::neighbors, S, W, and _NODE::weight.
Referenced by create_maze().
bool free_maze (Maze * maze)
free's the maze and all nodes
Parameters
return false on failure
References _MAZE::fastest_route, MAZE_SIZE, and _MAZE::nodes.
Referenced by flood_explore(), and main().
bool free_node (Node * node)
free's a node
Parameters
return false on failure
Node* get_node (Maze * maze, int x, int y)
get node by its position this is equlvelant to maze->nodes[x][y]
References MAZE_SIZE, and _MAZE::nodes.
Referenced by flood_explore(), flood_fill_custom(), maze_diff(), print_dist_maze(), print_maze(), print_maze_mouse(), print_pointer_maze(), read_from_file(), and sense().
Node* maze_diff (Maze * maze1, Maze * maze2)
goes through all the squares in two mazes and compares how many neighbors exist. the highest-difference unvisted node
References get_node(), MAZE_SIZE, _NODE::neighbors, and _NODE::visited.
Referenced by flood_explore().
void update_nodes (bool * walls, Direction dir, Node * no, Node * all, Node * all_neighbor)
uses the information from a sensor read and correctly adds or removes walls from nodes if sensors see a wall, it will remove a connection in the no_wall_node if the sensors don't see a wall, it will add a connection in the all_wall_node
References _NODE::neighbors.
Referenced by flood_explore().
bool visited (int row, int col, Direction dir, Maze * maze)
check if a node in a direction is visited looks up (row,col) in maze and checks its neighbors[dir] and returns if that neighbor is known
References _NODE::known, _NODE::neighbors, and _MAZE::nodes.