maze_io.h File Reference
#include `maze.h`
*
#include `mouse.h`
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
Functions
Maze * read_from_file (FILE *f)
void print_maze (Maze *maze)
void print_maze_mouse (Maze *maze, Mouse *mouse)
void print_pointer_maze (Maze *maze)
void print_neighbor_maze (Maze *maze)
void print_weight_maze (Maze *maze)
void print_dist_maze (Maze *maze)
Function Documentation
void print_dist_maze (Maze * maze)
duh
References _NODE::distance, get_node(), and MAZE_SIZE.
void print_maze (Maze * maze)
prints a maze
Parameters
maze the maze
References get_node(), MAZE_SIZE, S, and W.
Referenced by flood_fill_custom(), and main().
void print_maze_mouse (Maze * maze, Mouse * mouse)
prints a maze with a mouse in it
Parameters
mouse the mouse
maze the maze
References _MOUSE::col, get_node(), MAZE_SIZE, _MOUSE::row, S, and W.
Referenced by flood_explore().
void print_neighbor_maze (Maze * maze)
prints each node as a list of booleans EX) 0010 would mean on wall South 1011 would mean walls to the North, South, and West
References MAZE_SIZE, _NODE::neighbors, and _MAZE::nodes.
void print_pointer_maze (Maze * maze)
duh
References get_node(), and MAZE_SIZE.
void print_weight_maze (Maze * maze)
duh
References MAZE_SIZE, _MAZE::nodes, and _NODE::weight.
Referenced by flood_fill_custom().
Maze* read_from_file (FILE * f)
these functions read in a .mz file and parse it into a valid maze overall function to create a maze from file. any error will result in a null return.
Returns
a valid maze pointer to the maze struct, null on any sort of error
References create_maze(), E, get_node(), MAZE_SIZE, N, _NODE::neighbors, S, and W.
Referenced by main().