mouse.h File Reference
#include `maze.h`
*
#include <stdlib.h>
*
Classes
struct _MOUSE
depresents a mouse don't ever change the row/col of a mouse directly. This prevents it from working on the real robot use forward and turn_to_face to move the mouse around. Once those functions work on the real robot it will port over fluidly
Typedefs
typedef struct _MOUSE Mouse
Functions
Mouse * create_mouse ()
void execute_command (Mouse *mouse, char dir_char)
void forward (Mouse *mouse)
void update_pos (Direction dir, int *row, int *col)
void turn_to_face (Mouse *mouse, Direction d)
char dir_to_char (Direction dir)
Direction char_to_dir (char c)
bool * sense (Maze *maze, Mouse *mouse)
Typedef Documentation
typedef struct _MOUSE Mouse
Function Documentation
Direction char_to_dir (char c)
the obvious opposite of dir to char
References E, N, S, and W.
Referenced by execute_command().
Mouse* create_mouse ()
allocates and initializes a mouse be sure to free this mouse once you're done with it
Returns
the mouse
References _MOUSE::col, _MOUSE::dir, _MOUSE::row, and S.
Referenced by flood_explore(), and left_hand_follow().
char dir_to_char (Direction dir)
translate a Dir (integer 0=N 1=E 2=S 3=W) into the character representation
References E, N, S, and W.
Referenced by flood_fill_custom(), and left_hand_follow().
void execute_command (Mouse * mouse, char dir_char)
takes the given character and moves in that direction
Parameters
mouse the mouse to move with
dir_char the direciton do drive: 'N', 'E', 'S', or 'W'
References char_to_dir(), forward(), and turn_to_face().
Referenced by flood_explore().
void forward (Mouse * mouse)
base functions the emulate mouse movement calls
References _MOUSE::col, _MOUSE::dir, MAZE_SIZE, _MOUSE::row, and update_pos().
Referenced by execute_command(), and left_hand_follow().
bool* sense (Maze * maze, Mouse * mouse)
returns length 4 array of bools. must be freed
true means a wall exists
References _MOUSE::col, get_node(), _NODE::neighbors, and _MOUSE::row.
Referenced by flood_explore().
void turn_to_face (Mouse * mouse, Direction d)
literally just sets mouse position. pretty useless, but eventually will cause physical mouse to turn
References _MOUSE::dir.
Referenced by execute_command().
void update_pos (Direction dir, int * row, int * col)
update row and col numbers given based on dir
References E, N, S, and W.
Referenced by flood_explore(), and forward().