mouse.c File Reference
#include `mouse.h`
*
Functions
Mouse * create_mouse ()
void forward (Mouse *mouse)
void update_pos (Direction dir, int *row, int *col)
char dir_to_char (Direction dir)
bool * sense (Maze *maze, Mouse *mouse)
Function Documentation
Mouse* create_mouse ()
creates a mouse
References _MOUSE::col, _MOUSE::dir, _MOUSE::row, and S.
Referenced by flood_explore(), and left_hand_follow().
char dir_to_char (Direction dir)
translate a Dir (integer 0=N 1=E 2=S 3=W) into the character representation
References E, N, S, and W.
Referenced by flood_fill(), and left_hand_follow().
void forward (Mouse * mouse)
base functions the emulate mouse movement calls
References _MOUSE::col, _MOUSE::dir, _MOUSE::row, and update_pos().
Referenced by left_hand_follow().
bool* sense (Maze * maze, Mouse * mouse)
true means a wall exists
References _MOUSE::col, get_node(), _NODE::neighbors, and _MOUSE::row.
Referenced by flood_explore().
void update_pos (Direction dir, int * row, int * col)
update row and col numbers given based on dir
References E, N, S, and W.
Referenced by flood_explore(), and forward().