solvers.h File Reference
#include `maze.h`
*
#include `mouse.h`
*
#include `maze_io.h`
*
#include <stdbool.h>
*
Functions
void A_star (Maze *maze, int x0, int y0, int x1, int y1)
Node * closest_unknown (Maze *maze)
void update_neighbors (Node *node)
void flood_explore (Maze *kmaze)
starts at 0,0 and explores the whole maze kmaze is the known maze, and is used to `read the sensors` The mouse solves the maze after sensing each new square solves assuming ALL walls, and assuming NO walls when the solution for those two mazes are the same, then it knows the fastest route
bool flood_fill (Maze *maze, char *path)
bool flood_fill_custom (Maze *maze, char *path, int r0, int c0, int r1, int c1)
void explore_neighbors (Node *node, Node *goal, int weight, bool *success)
void left_hand_follow (Maze *maze)
void mark_position (Mouse *mouse, Maze *maze)
bool blocked (Mouse *mouse, Maze *maze)
bool blocked_in_dir (int row, int col, Direction dir, Maze *maze)
void choose_direction (Mouse *mouse, Maze *maze)
bool atCenter (Mouse *mouse)
bool isCenter (int row, int col)
Function Documentation
void A_star (Maze * maze, int x0, int y0, int x1, int y1)
functions for exploring and solving mazes
bool atCenter (Mouse * mouse)
checks if the mouse is int the center 4 squares of the maze
Parameters
mouse the mouse
References _MOUSE::col, isCenter(), and _MOUSE::row.
Referenced by left_hand_follow().
bool blocked (Mouse * mouse, Maze * maze)
checks the mouses direction, and compares it to the mazes walls. For example, if the mouse is facing north, and the node it's on has a null north pointer, then there's a wall
Parameters
mouse the mouse
maze the maze
References blocked_in_dir(), _MOUSE::col, _MOUSE::dir, and _MOUSE::row.
bool blocked_in_dir (int row, int col, Direction dir, Maze * maze)
checks a direction, and compares it to the mazes walls. For example, if the mouse is facing north, and the node it's on has a null north pointer, then there's a wall
Parameters
mouse the mouse
maze the maze
References _MOUSE::col, _MOUSE::dir, _NODE::neighbors, _MAZE::nodes, and _MOUSE::row.
Referenced by blocked(), and left_hand_follow().
void choose_direction (Mouse * mouse, Maze * maze)
chooses a direction. If possible, it picks an unvisited node, otherwise it picks a random one it's been too already
Parameters
mouse the mouse
Node* closest_unknown (Maze * maze)
void explore_neighbors (Node * node, Node * goal, int weight, bool * success)
this assigns n->weight+1 to each neighbor, and recursively calls it on all valid neighbors
Parameters
node the node to explore the neighbors of
goal the node you want to find a path to
weight the weight to set the node to
success should be false to start, and will be set to true if path to goal is found
References explore_neighbors(), _NODE::known, _NODE::neighbors, and _NODE::weight.
Referenced by explore_neighbors(), and flood_fill_custom().
void flood_explore (Maze * kmaze)
starts at 0,0 and explores the whole maze kmaze is the known maze, and is used to `read the sensors` The mouse solves the maze after sensing each new square solves assuming ALL walls, and assuming NO walls when the solution for those two mazes are the same, then it knows the fastest route
Parameters
kmaze the known maze. in reality this won't exist because the sensors can read from the real world
References _MOUSE::col, _NODE::col, create_maze(), create_mouse(), E, execute_command(), _MAZE::fastest_route, flood_fill(), flood_fill_custom(), free_maze(), get_node(), mark_position(), maze_diff(), MAZE_SIZE, N, _NODE::neighbors, PATH_SIZE, print_maze_mouse(), _MOUSE::row, _NODE::row, S, sense(), update_nodes(), update_pos(), and W.
Referenced by main().
bool flood_fill (Maze * maze, char * path)
set starting point 0,0 & S. depth-first search of all nodes in the grid, adding 1 each time. once all nodes are discovered, the path is solved by going backwards from the center to the lowest neighbor each time
Parameters
maze maze to solve
path an allocate char* of at least PATH_SIZE to store the solution in
References flood_fill_custom().
Referenced by flood_explore().
bool flood_fill_custom (Maze * maze, char * path, int r0, int c0, int r1, int c1)
this one also allows you to specify a starting position other tha 0,0
Parameters
maze the maze the solve
path an allocate char* of at least PATH_SIZE to store the solution in
r0 the row to start in
c0 the column to start in
r1 the row to end in
c1 the column to end in
References dir_to_char(), explore_neighbors(), get_node(), _NODE::known, MAZE_SIZE, N, _NODE::neighbors, _MAZE::nodes, PATH_SIZE, print_maze(), print_weight_maze(), and _NODE::weight.
Referenced by flood_explore(), and flood_fill().
bool isCenter (int row, int col)
checks if the row col is at center
Parameters
mouse the mouse
References MAZE_SIZE.
Referenced by atCenter().
void left_hand_follow (Maze * maze)
set starting point to 0,0. follow left hand wall
Parameters
maze maze to solve
References atCenter(), blocked_in_dir(), _MOUSE::col, create_mouse(), _MOUSE::dir, dir_to_char(), _MAZE::fastest_route, forward(), _NODE::known, mark_position(), _MAZE::nodes, and _MOUSE::row.
void mark_position (Mouse * mouse, Maze * maze)
marks the mouses given position as known
Parameters
mouse the mouse
maze the maze
References _MOUSE::col, _NODE::known, _MAZE::nodes, and _MOUSE::row.
Referenced by flood_explore(), and left_hand_follow().
void update_neighbors (Node * node)
Not used