solvers.c File Reference
#include `solvers.h`
*
Macros
#define min(a, b) ((a) < (b) ? (a) : (b))
Functions
void flood_explore (Maze *kmaze)
starts at 0,0 and explores the whole maze kmaze is the known maze, and is used to `read the sensors` The mouse solves the maze after sensing each new square solves assuming ALL walls, and assuming NO walls when the solution for those two mazes are the same, then it knows the fastest route
void flood_fill (Maze *maze, char *path)
void flood_fill_custom (Maze *maze, char *path, int r0, int c0)
void explore_neighbors (Node *node, Node *goal, int weight, bool *success)
void left_hand_follow (Maze *maze)
void mark_position (Mouse *mouse, Maze *maze)
bool blocked (Mouse *mouse, Maze *maze)
bool blocked_in_dir (int row, int col, Direction dir, Maze *maze)
bool atCenter (Mouse *mouse)
bool isCenter (int row, int col)
Macro Definition Documentation
#define min(a, b) ((a) < (b) ? (a) : (b))
solvers.h
Author
Peter Mitrano
Function Documentation
bool atCenter (Mouse * mouse)
checks if the mouse is int the center 4 squares of the maze
Parameters
mouse the mouse
References _MOUSE::col, isCenter(), and _MOUSE::row.
Referenced by left_hand_follow().
bool blocked (Mouse * mouse, Maze * maze)
checks the mouses direction, and compares it to the mazes walls. For example, if the mouse is facing north, and the node it's on has a null north pointer, then there's a wall
Parameters
mouse the mouse
maze the maze
References blocked_in_dir(), _MOUSE::col, _MOUSE::dir, and _MOUSE::row.
bool blocked_in_dir (int row, int col, Direction dir, Maze * maze)
checks a direction, and compares it to the mazes walls. For example, if the mouse is facing north, and the node it's on has a null north pointer, then there's a wall
Parameters
mouse the mouse
maze the maze
References _MOUSE::col, _MOUSE::dir, _NODE::neighbors, _MAZE::nodes, and _MOUSE::row.
Referenced by blocked(), and left_hand_follow().
void explore_neighbors (Node * node, Node * goal, int weight, bool * success)
this assigns n->weight+1 to each neighbor, and recursively calls it on all valid neighbors
Parameters
node the node to explore the neighbors of
goal the node you want to find a path to
weight the weight to set the node to
success should be false to start, and will be set to true if path to goal is found
References explore_neighbors(), _NODE::known, _NODE::neighbors, and _NODE::weight.
Referenced by explore_neighbors(), and flood_fill_custom().
void flood_explore (Maze * kmaze)
starts at 0,0 and explores the whole maze kmaze is the known maze, and is used to `read the sensors` The mouse solves the maze after sensing each new square solves assuming ALL walls, and assuming NO walls when the solution for those two mazes are the same, then it knows the fastest route
Parameters
kmaze the known maze. in reality this won't exist because the sensors can read from the real world
use args to the make command to print more information ARGS=-DDEBUG prints just the mouse position ARGS=-DDEBUG_FULL prints mazes, paths, and mouse positions ARGS=-DDEBUG_PATH prints just paths
References _MOUSE::col, create_maze(), create_mouse(), E, execute_command(), _MAZE::fastest_route, flood_fill(), flood_fill_custom(), free_maze(), get_node(), MAZE_SIZE, N, _NODE::neighbors, PATH_SIZE, _MOUSE::row, S, sense(), update_pos(), and W.
Referenced by main().
void flood_fill (Maze * maze, char * path)
set starting point 0,0 & S. depth-first search of all nodes in the grid, adding 1 each time. once all nodes are discovered, the path is solved by going backwards from the center to the lowest neighbor each time
Parameters
maze maze to solve
path an allocate char* of at least PATH_SIZE to store the solution in
References flood_fill_custom().
Referenced by flood_explore().
void flood_fill_custom (Maze * maze, char * path, int r0, int c0)
this one also allows you to specify a starting position other tha 0,0
Parameters
maze the maze the solve
path an allocate char* of at least PATH_SIZE to store the solution in
r0 the row to start in
c0 the column to start in
References dir_to_char(), explore_neighbors(), get_node(), _NODE::known, MAZE_SIZE, N, _NODE::neighbors, _MAZE::nodes, PATH_SIZE, print_maze(), print_weight_maze(), and _NODE::weight.
Referenced by flood_explore(), and flood_fill().
bool isCenter (int row, int col)
checks if the row col is at center
Parameters
mouse the mouse
References MAZE_SIZE.
Referenced by atCenter().
void left_hand_follow (Maze * maze)
set starting point to 0,0. follow left hand wall
Parameters
maze maze to solve
References atCenter(), blocked_in_dir(), _MOUSE::col, create_mouse(), _MOUSE::dir, dir_to_char(), _MAZE::fastest_route, forward(), _NODE::known, mark_position(), _MAZE::nodes, and _MOUSE::row.
void mark_position (Mouse * mouse, Maze * maze)
marks the mouses given position as known
Parameters
mouse the mouse
maze the maze
References _MOUSE::col, _NODE::known, _MAZE::nodes, and _MOUSE::row.
Referenced by left_hand_follow().